matrix:
  include:
  - language: ruby
    name: Bundler (rvm 2.5)
    rvm: 2.5
    before_install:
    - gem install bundler
  - language: ruby
    name: Bundler (rvm 2.6)
    rvm: 2.6
    before_install:
    - gem install bundler
  - language: ruby
    name: Bundler (rvm 2.7)
    rvm: 2.7
    before_install:
    - gem install bundler
  - language: ruby
    name: Bundler (rvm 3.0)
    rvm: 3.0
    before_install:
    - gem install bundler
  - language: ruby
    name: Rubocop (rvm 2.5)
    rvm: 2.5
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop.git
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Rubocop (rvm 2.6)
    rvm: 2.6
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop.git
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Rubocop (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop.git
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Rubocop (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop.git
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Reek (rvm 2.5)
    rvm: 2.5
    before_install:
    - git clone https://github.com/TravisToolbox/reek.git
    install:
    - "./reek/install.sh"
    script:
    - "./reek/scan.sh"
  - language: ruby
    name: Reek (rvm 2.6)
    rvm: 2.6
    before_install:
    - git clone https://github.com/TravisToolbox/reek.git
    install:
    - "./reek/install.sh"
    script:
    - "./reek/scan.sh"
  - language: ruby
    name: Reek (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/reek.git
    install:
    - "./reek/install.sh"
    script:
    - "./reek/scan.sh"
  - language: ruby
    name: Reek (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/reek.git
    install:
    - "./reek/install.sh"
    script:
    - "./reek/scan.sh"
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io,https://github.com/DevelopersToolbox/caretaker"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: lf180dIS6rX+M1V9YT3KHvSSwE/BeW3s2XLRiyx8L4ruwPOpXv9YkdjpGVapdA+dJpXnFMbYUiNyXxbjggvguEycSuXat57EVHQzuXn2dkgDAH0sKIRoCXuTxQfbYUKbI/3jGXafQC7YH3Lhw2Laza/R4b7281zj8QFtGnQNaeqetDJIBczsXtiUjjWkwywUh9UNu+W5j5vGY67v4DpupFNJj3zbmsQlnD4C4py8OlAsza1sfXbtd4Di+x4+MDg4nZCY7UKTY1JZGMiTuO8y4RByRheMsZKJjgv1VqA/q75vNSiXC9c1MkSJHpjHtiPLdUg8JLtl0kRgfZriuueXO/PtA0BxCglZfjLxn9FsSj+UN9Xd5pJYGbT+mzrguSINk7Y2mqkfssTjJwgO41Pp8F0IaAoKK7BYJ4DL6Cfq2pyYew7h4tbyZuipYrK2r9b5qhwlWnPgBuyQry700U1a888fy94MU9EzTutjhHpxRgdqnMXGM10C2DpaDo5J36ApwLOJRGNk8VYREbszqZ55PuZet7hv1tbLBhhfDaKxVOy89Nk5Oluubk2rLtave7YxMU+AUdEiHIVqY66caHw1hqXqCBPGI0V7hWLykctZX+KAf0CSPJMRY6U2B53ST4pb3mvUy5zZj7au+t8TKBPdEXa4iVd2VH7fDDVuftvud1M=
